CREATE DATABASE IF NOT EXISTS testdb;
CREATE DATABASE IF NOT EXISTS devdb;
CREATE DATABASE IF NOT EXISTS proddb;
CREATE USER 'zenusr'@'localhost' IDENTIFIED BY 'userP@ss2024';
GRANT ALL PRIVILEGES ON `testdb`.* TO 'zenusr'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `devdb`.* TO 'zenusr'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
