# Services
services:

  # Nginx Service
  nginx:
    container_name: web
    image: nginx:alpine
    ports:
      - 8080:80
    restart: always
    environment:
      - TZ=America/Edmonton
    links:
      - php
    volumes:
      #- ./www/html/:/var/www/html/
      - ./www/typecho/:/var/www/html/
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - php
      - mariadb
    networks:
      - lemp-net

  # PHP-FPM Service
  php:
    container_name: php8
    build: php
    expose:
      - 9000
    restart: always
    environment:
      - TZ=America/Edmonton
    volumes:
      #- ./www/html/:/var/www/html/
      - ./www/typecho/:/var/www/html/
      - ./php/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
    networks:
      - lemp-net

  # MariaDB Service
  mariadb:
    container_name: mariadb
    image: mariadb:11.4
    expose:
      - 3306:3306
    restart: always
    env_file:
      - ./db/env/mysql.env
    volumes:
      #- ./init/initdb-html.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./init/initdb-typecho.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./db/data/:/var/lib/mysql/
      - ./db/logs/:/var/log/mysql/
    networks:
      - lemp-net


  # phpMyAdmin Service
  phpmyadmin:
      container_name: phpadm
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      ports:
        - 8090:80
      environment:
        PMA_HOST: mariadb
      depends_on:
        - mariadb
      networks:
        - lemp-net

# Networks
networks:
  lemp-net:
